#! /bin/bash
ulimit -n 4034660
ulimit -c unlimited
dockerroot="/data/docker"

function help()
{
    echo "Usage docker [start|stop|restart|rmc]"
    exit 1
}

function isRun()
{
    if [ `ps -ef | grep docker | grep daemon | wc -l` -gt 0 ]; then
        echo 1
    else
        echo 0
    fi
}

function start()
{
    if [ `isRun` -eq 1 ]; then
        echo "docker daemon is running."
    else
        if [ `ifconfig | grep docker0 | wc -l` -eq 0 ]; then
            brctl addbr docker0
            #brctl addif docker0 eth0
            ip link set dev docker0 up
            ip addr add 172.17.42.1/16 dev docker0
        fi
        if [ ! -d "$dockerroot" ]; then
            mkdir -p $dockerroot
        fi
		#--registry-mirror=http://lc13579443.m.alauda.cn
		#--insecure-registry "uworkdocker.io:5000" 
		#--default-ulimit="nofile=204800:409600  nproc=20480:40960" 
        nohup docker daemon --storage-opt dm.basesize=200G -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --api-cors-header=true --iptables=true --graph=$dockerroot >> $dockerroot/docker.log &
        if [ $? -eq 0 ]; then
            echo "start sucessfully."
        else
            echo "start failed."
        fi        
    fi
}

function stop()
{
    if [ `isRun` -gt 0 ]; then
        ps -ef | grep docker | grep daemon | awk '{print $2}' | xargs kill
        echo -n "stopping..."
        waitcnt=0
        while true; do
            flag=`isRun`
            if [ $flag -gt 0 ]; then
                echo -n "."
                sleep 2
                waitcnt=$[$waitcnt+1]
                if [ $waitcnt -eq 10 ]; then
                    ps -ef | grep docker | grep daemon | awk '{print $2}' | xargs kill -9
                fi
            else
                echo "successfully."
                break
            fi
        done

    else
        echo "docker is not running."
    fi
}

function rmc()
{
    if [ `isRun` -gt 0 ]; then
       docker rm $(docker ps -a -q)
	   #docker ps -aq -f status=exited | xargs docker rm

    else
        echo "docker is not running."
    fi
}

case $1 in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
	rmc)
        rmc 
    ;;
    *)
        help
    ;;
esac
